# Generated by Django 3.1 on 2020-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
